### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#10]
add steps about how to properly setup the project

**Comment by Beingfarazkhan** [comment]
I would like to Contribute Towards this issue 🚀

**Comment by mnnkhndlwl** [comment]
assigned while making pr please add relevant screenshot to show your work

**Comment by mnnkhndlwl** [comment]
happy contributing

**Comment by Beingfarazkhan** [comment]
Thanks : )

**Comment by AbhiPatel10** [comment]
If you are working on documentation then please make another file Name `CONTRIBUTON.md`. and put all information about contribution in that file.

Only add application overview and guidance in main `Readme` file

**Comment by Beingfarazkhan** [comment]
i made a CONTRIBUTING.md and a CODE_OF_CONDUCT.md what else should i add to the documentation?

**Comment by mnnkhndlwl** [comment]
commit those changes and create a pull request and let me check

**Comment by mnnkhndlwl** [comment]
@Beingfarazkhan
