### ISSUE TITLE
make the application responsive

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#12]
currently, the application is not responsive 
make it responsive for mobile devices

**Comment by Biswajit-Behera** [comment]
Could I contribute to this issue??

**Comment by mnnkhndlwl** [comment]
You can work on issues only after 15th Feb till then setup the app on your system

**Comment by anvi2901** [comment]
I want to work on this issue under JWOC!

**Comment by Biswajit-Behera** [comment]
I want to work on this issue under JWOC

**Comment by mnnkhndlwl** [comment]
@anvi2901 you can work on other issues

**Comment by Biswajit-Behera** [comment]
Will work upon it & will ask if I had any confusion.

**Comment by Biswajit-Behera** [comment]
Thank You @mnnkhndlwl 
Will give you the updates and Will ask if I have any doubts.

**Comment by sandeeprawat28** [comment]
Please assign this issue to me

**Comment by mnnkhndlwl** [comment]
@sandeeprawat28 it's already assigned to @Biswajit-Behera you can raise your own issues

**Comment by Biswajit-Behera** [comment]
@mnnkhndlwl If I find any issue I will raise it.

**Comment by mnnkhndlwl** [comment]
@Biswajit-Behera as you are working on responsiveness make sure you pull frequently because others people are also working on ui so just to make sure everything is working fine

**Comment by Biswajit-Behera** [comment]
> @Biswajit-Behera as you are working on responsiveness make sure you pull frequently because others people are also working on ui so just to make sure everything is working fine

Will Give my update or PR tonight or tomorrow morning!

**Comment by Biswajit-Behera** [comment]
> @Biswajit-Behera as you are working on responsiveness make sure you pull frequently because others people are also working on ui so just to make sure everything is working fine

Sorry for the late response!

**Comment by sarkartanmay393** [comment]
@mnnkhndlwl If this issue is not yet touched, I would Iike to contribute to it under JWOC.

**Comment by mnnkhndlwl** [comment]
@sarkartanmay393 currently @Biswajit-Behera is working on this issue

**Comment by Biswajit-Behera** [comment]
> @sarkartanmay393 currently @Biswajit-Behera is working on this issue

I am currently working on this and facing some problems related to firebase so it took time...
Sorry IK it took time!

**Comment by mnnkhndlwl** [comment]
@Biswajit-Behera how's everything going on

**Comment by Biswajit-Behera** [comment]
> @Biswajit-Behera how's everything going on

Sorry for the delay, actually I was suffering from the Dengue. So I was unable to do anything. Please give me time till the 1st of March, I will do it!

**Comment by mnnkhndlwl** [comment]
no problem take your time

**Comment by Biswajit-Behera** [comment]
> no problem take your time

Extremely sorry for the delay!

**Comment by mnnkhndlwl** [comment]
@Biswajit-Behera today is your last day to make pr i cannot give you more time
