### ISSUE TITLE
Want to add some documentation 

### ISSUE THREAD

**Issue by Sowham-3098** [mnnkhndlwl/mern_youtube_clone#13]
1. code_of_conduct.md
2. LICENSE.md
3. contributing.md
4. contributors profile section in README.md

**Comment by mnnkhndlwl** [comment]
You can work on the issues after 15 th feb

**Comment by Sowham-3098** [comment]
ok

**Comment by Sowham-3098** [comment]
Assign this to me under JWOC

**Comment by mnnkhndlwl** [comment]
@Sowham-3098 currently someone else is working on documentation first let that person complete his/her work then I will assign this issue 
If anything is remaining you can add them in documentation

**Comment by mnnkhndlwl** [comment]
@Sowham-3098 if you want to add something to the documentation you can add will merge your changes

**Comment by Sowham-3098** [comment]
Ok , I will see into it tomorrow.You can assign it to me.

**Comment by mnnkhndlwl** [comment]
@Sowham-3098 bro can you make readme like in this readme https://github.com/aman34503/Go-Airbnb

**Comment by Sowham-3098** [comment]
Yeah I can try..

**Comment by mnnkhndlwl** [comment]
https://github.com/github/docs also like this repo they have a separating contributing section in readme and on clicking on contributing guide we can see all the steps how to contribute

**Comment by Sowham-3098** [comment]
@mnnkhndlwl ,Which tech-stacks are used in your project?

**Comment by mnnkhndlwl** [comment]
already mentioned in readme

**Comment by mnnkhndlwl** [comment]
# ReactJS in the frontend
# State management in the frontend using Redux & Redux Toolkit
# Styled components with more emphasis on custom CSS & little bit of Material UI & Icons
# Video & Image upload using firebase storage
# Search, Like & Dislike, Subscribe a channel & Comment a video features
# Video recommendations on the video page
# Light / Dark Mode toggling
# Axios http client
# JWT cookie authentication
# Hashed password saving in the MongoDB database
# Login & Signup with custom Email & Password, Google OAuth using firebase authentication
# RESTful API using ExpressJS and MongoDB with mongoose
# Error handler & Protected routes

**Comment by Sowham-3098** [comment]
ok
