### ISSUE TITLE
Update Project Tittle and add Favicon 

### ISSUE THREAD

**Issue by AbhiPatel10** [mnnkhndlwl/mern_youtube_clone#15]
Please Update Title From `nakli youtube` to `YouTube` 

Also Change  Favicon of This project to YouTube Icon.

@mnnkhndlwl Please add `Goodfirstissue` and `JWOC` labels here and anyone can take this issue. 👍

![image](https://user-images.githubusercontent.com/76242769/218792756-a4135b1e-8270-48b3-9ba0-70cf4a35663b.png)

**Comment by Awesomeasma** [comment]
I want to work on this issue under JWOC

**Comment by mnnkhndlwl** [comment]
assigned

**Comment by Awesomeasma** [comment]
Thank you !
