### ISSUE TITLE
[Feature]: add some effects on search bar

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#18]
### Describe the solution you'd like

when we click on search bar in youtube there will be a blue border applied on the search bar do the same thing here

**Comment by gnaneshwar718** [comment]
I want to contribute on it under jwoc

**Comment by mnnkhndlwl** [comment]
@gnaneshwar718 already assigned you one work on that first

**Comment by gnaneshwar718** [comment]
in the same project no

**Comment by gnaneshwar718** [comment]
Yea i saw it now sorry

**Comment by i-am-SnehaChauhan** [comment]
"I want to work on this issue under JWOC"

**Comment by mnnkhndlwl** [comment]
@i-am-SnehaChauhan assigned

**Comment by singhalaman23** [comment]
I would like to work on this issue under JWOC if it's still not resolved. (Currently I have not been assigned any issue in this project)

**Comment by mnnkhndlwl** [comment]
@i-am-SnehaChauhan are you still working on the issue

**Comment by mnnkhndlwl** [comment]
@i-am-SnehaChauhan your time is up if you don't reply within 2-3 hours according to the rules I will assign this issue to someone else

**Comment by i-am-SnehaChauhan** [comment]
> @i-am-SnehaChauhan your time is up if you don't reply within 2-3 hours according to the rules I will assign this issue to someone else

yes assign someone else.

**Comment by manya0210** [comment]
hello..I want to work on this issue under jwoc

**Comment by mnnkhndlwl** [comment]
@manya0210 are you still working on this issue

**Comment by arjunchoudhury07** [comment]
I would like to contribute under JWOC

**Comment by Hrx4** [comment]
assign this issue to me , under JWOC
