### ISSUE TITLE
The server folder is empty

### ISSUE THREAD

**Issue by Regis-Loyaute** [mnnkhndlwl/mern_youtube_clone#2]
Is that normal ?

**Comment by mnnkhndlwl** [comment]
Server repo :- https://github.com/mnnkhndlwl/youtube-backend

**Comment by Regis-Loyaute** [comment]
Thanks

**Comment by mnnkhndlwl** [comment]
Yeah it's possible to store them locally using multer but I had to deploy it on renderer.com and you will not get storage options on free plan so I used firebase here
