### ISSUE TITLE
[Feature]: align the loading spinner of home screen at center

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#21]
### Describe the solution you'd like

currently loading spinner of home screen is not aligned at center 
make sure while making pull request you add relevant screenshots or videos

**Comment by arjunchoudhury07** [comment]
I want to contribute on it under jwoc

**Comment by mnnkhndlwl** [comment]
@arjunchoudhury07 assigned
