### ISSUE TITLE
[Feature]: add a cross icon on the warning component in sign page

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#26]
### Describe the solution you'd like

after warning sign is shown user should be able to close that by clicking on a cross icon

**Comment by arjunchoudhury07** [comment]
I want to contribute

**Comment by mnnkhndlwl** [comment]
@arjunchoudhury07 assigned

**Comment by mnnkhndlwl** [comment]
while making pr please add a video to show that it's working

**Comment by arjunchoudhury07** [comment]
Do you mean to add a cross icon on the top left side of the yellow box?

![signin](https://user-images.githubusercontent.com/92199877/219598912-df5b7f4e-06c5-49f8-a820-8b0fe384d8bb.png)

**Comment by mnnkhndlwl** [comment]
yep
