### ISSUE TITLE
[Feature]: add loading spinner to search page 

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#28]
### Describe the solution you'd like

while searching for a video a loading spinner should be shown

**Comment by mnnkhndlwl** [comment]
you can use loading spinner present in utils folder

**Comment by mecivil** [comment]
I am ready to take up this issue under JWOC once you merge my previous PR

**Comment by mnnkhndlwl** [comment]
@mecivil assigned
