### ISSUE TITLE
add a loading spinner in home screen

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#3]
add a lot spinner in home screen the loading spinner should be shown while server fetches videos 
A custom spinner is already there in utils folder just use that  or if you can also modify that spinner

**Comment by i-am-SnehaChauhan** [comment]
I am new to open source and have experience in web-D.
I  would like to contribute.

**Comment by mnnkhndlwl** [comment]
@i-am-SnehaChauhan you can contribute after 15 feb till then setup the app on your system

**Comment by Tushar-go** [comment]
hey I want to work on this issue please assign me this issue under jwoc

**Comment by mecivil** [comment]
I want to work on this issue under JWOC
