### ISSUE TITLE
[Feature]: make a admin user

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#37]
### Describe the solution you'd like

make a user
this user should be able to see delete icons on all videos
this user should be able to delete all videos

**Comment by deepbeatz** [comment]
I want to work on this under JWOC

**Comment by mecivil** [comment]
I want to work for it under JWOC

**Comment by mnnkhndlwl** [comment]
@mecivil assigned

**Comment by mecivil** [comment]
I won't be able to do it within stipulated tine.Sorry for that.Please assign someone else.

**Comment by Priyamakeshwari** [comment]
I would like to work on this issue under JWOC

**Comment by mnnkhndlwl** [comment]
@Priyamakeshwari assigned !

**Comment by sarkartanmay393** [comment]
@mnnkhndlwl If there is no PR raised in the past 8days, I would like to contribute to it under JWOC

**Comment by mnnkhndlwl** [comment]
@Priyamakeshwari are you still working on this issue??

**Comment by mnnkhndlwl** [comment]
@sarkartanmay393 assigning you this issue
