### ISSUE TITLE
[Feature]: make an api for report an issue

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#38]
### Describe the solution you'd like

what I want is user should be able to report an issue 
you have to make an API for adding the issue 
list all the issues 
if u want more clarification contact me on discord

**Comment by deepbeatz** [comment]
I want to work on this under JWOC

**Comment by mecivil** [comment]
I want to work for it under JWOC

**Comment by mnnkhndlwl** [comment]
@deepbeatz assigned

**Comment by deepbeatz** [comment]
@mnnkhndlwl will get back to u asap

**Comment by mecivil** [comment]
I would like to work on this issue under JWOC

**Comment by sarkartanmay393** [comment]
@mnnkhndlwl I would like to work under JWOC, after you review #66

**Comment by mnnkhndlwl** [comment]
@sarkartanmay393 assigned
