### ISSUE TITLE
improve layout of home screen

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#4]
![image](https://user-images.githubusercontent.com/75252077/218263827-a84a0faa-0650-4457-ab44-240c6d43f272.png)
improve the layout of home screen currently if there are only two videos there's a lot of distance between them

**Comment by Atul-8115** [comment]
I want to work on this issue please assign it to me

**Comment by mecivil** [comment]
I want to work on this under JWOC
