### ISSUE TITLE
[Bug]:  Video overlay to the Navbar

### ISSUE THREAD

**Issue by AbhiPatel10** [mnnkhndlwl/mern_youtube_clone#40]
### Describe the bug

![image](https://user-images.githubusercontent.com/76242769/219991983-44e55223-fa66-4f82-b86b-1adf91f0b039.png)

### To Reproduce

Go to Home page
Click on any video
Scroll down and you can see Video overlap to the navbar

### Expected Behavior

Navbar must appear on first 

We can add Z-index to Navbar for solving this Bug

### Desktop (please complete the following information)

All

### Additional context

I  want to work on this issue under JWOC

**Comment by sarkartanmay393** [comment]
@mnnkhndlwl If this is a important issue to you, I want to work on it under JWOC.
