### ISSUE TITLE
[Bug]:  Make Sidebar Responsive

### ISSUE THREAD

**Issue by AbhiPatel10** [mnnkhndlwl/mern_youtube_clone#47]
### Describe the bug

make sidebar responsive also make it sticky as per youTube. 

All routes and Icons should come dynamically.

### Expected Behavior

Sidebar should be responsive

### Additional context

Please add JWOC And Hard label on this issue.

Anyone can take this issue.

_No response_

**Comment by mnnkhndlwl** [comment]
@AbhiPatel10 assigned
