### ISSUE TITLE
[Feature]: implement feature to edit user info

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#49]
### Describe the solution you'd like

edit user info page is already been made you have to connect backend with that page 
no need to edit users's profile photo

**Comment by sarkartanmay393** [comment]
@mnnkhndlwl I would like to take it over, after you review my [Share Button](https://github.com/mnnkhndlwl/mern_youtube_clone/pull/55) PR.
