### ISSUE TITLE
Add a custom scrollbar

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#5]

**Comment by Biswajit-Behera** [comment]
I want to work on this issue under JWOC!

**Comment by mnnkhndlwl** [comment]
@Biswajit-Behera already assigned you  a issue work on that first

**Comment by parv15** [comment]
I'm interested to contribute this issue. Can you assign me?

**Comment by mecivil** [comment]
I want to work on this under JWOC

**Comment by singhalaman23** [comment]
I want to work on this issue under JWOC

**Comment by mnnkhndlwl** [comment]
@gnaneshwar718 are you still working on the issue??

**Comment by singhalaman23** [comment]
@mnnkhndlwl Do consider assigning me this issue under JWOC if it doesn't get resolved by the current assignee.

**Comment by mnnkhndlwl** [comment]
@gnaneshwar718 you have exceeded time limit required to resolve this issue if you don't reply within 2-3 hours i have to assign this issue to someone else

**Comment by mnnkhndlwl** [comment]
@gnaneshwar718 reply or i have to assign this issue to someone else

**Comment by VaibhavTalkhande** [comment]
I want to work on issues under jwoc

**Comment by mnnkhndlwl** [comment]
@VaibhavTalkhande assigned

**Comment by singhalaman23** [comment]
> @VaibhavTalkhande assigned

looks like you are not following the rules

**Comment by VaibhavTalkhande** [comment]
@singhalaman23  what happened?

**Comment by mnnkhndlwl** [comment]
@singhalaman23 there are other people also who want to contribute
i was waiting for the current assignee to reply which he didn't so assigned it to one who commented after that 
don't worry i am raising new issues you can work them

**Comment by VaibhavTalkhande** [comment]
I  have added a scroll bar
