### ISSUE TITLE
Add a dummy mic button EXACTLY like YouTube and redesign the search bar.

### ISSUE THREAD

**Issue by singhalaman23** [mnnkhndlwl/mern_youtube_clone#50]
### Describe the solution you'd like

I want to redesign the search bar so that it looks exactly like youtube's search bar, by adding the blue border on it.
I also want to add a dummy mic button just beside the search bar to make the navbar even more like the original youtube's navbar.
In short, i want to create this (along with the MIC button)
![image](https://user-images.githubusercontent.com/99071072/221368442-742c0cef-991e-46f9-8c33-0a31ac0d0e1d.png)

Please assign this issue to me under JWOC and do add the relevant tags.

**Comment by mnnkhndlwl** [comment]
@singhalaman23 are you still working on the issue??

**Comment by singhalaman23** [comment]
> @singhalaman23 are you still working on the issue??

@mnnkhndlwl Sorry.... got some urgent college work, will not be able to resolve the issue this time.

**Comment by sarkartanmay393** [comment]
@mnnkhndlwl Assign me it under JWOC.

**Comment by mnnkhndlwl** [comment]
@sarkartanmay393 assigned

**Comment by mecivil** [comment]
I would like to work on this issue under JWOC

**Comment by dibyendu02** [comment]
I would like to work on this issue under JWOC
