### ISSUE TITLE
[Feature]: if user is subscribed then subscribed button should be shown in grey colour other wise it should be red

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#51]
### Describe the solution you'd like

https://user-images.githubusercontent.com/75252077/215592578-6ba38684-3016-45c9-9c5f-05e620f91227.png

**Comment by Rubyseher** [comment]
can u assign me this under JWOC

**Comment by mnnkhndlwl** [comment]
@Rubyseher assigned

**Comment by mnnkhndlwl** [comment]
@Rubyseher are you still working on the issue??

**Comment by Rubyseher** [comment]
It's done 
I'll just make a pr once I get home
