### ISSUE TITLE
make a page to edit the user info

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#6]
just make a separate page to edit the user info

**Comment by parv15** [comment]
I'm interested to contribute this issue. Can you assign me?

**Comment by avdhendra** [comment]
can you assign me this issue as JWOC contribution

**Comment by mnnkhndlwl** [comment]
@avdhendra assigned

**Comment by avdhendra** [comment]
can you tell me what things need to be in editing page for profile

**Comment by avdhendra** [comment]
![Screenshot (448)](https://user-images.githubusercontent.com/71092461/219902378-bdf7a153-91c2-46e7-be8f-2e273bb09a04.png)
i made this much but dont know what needs to be editing

**Comment by mnnkhndlwl** [comment]
Bro this is enough make a pr and let me review the code

**Comment by avdhendra** [comment]
do i create new branch or pull request on same branch

**Comment by avdhendra** [comment]
check the pr i made one

**Comment by avdhendra** [comment]
can your merge the request after my name and jwoc2023 naming
