### ISSUE TITLE
[Update]:  Make a separate file for MongoDb Connection

### ISSUE THREAD

**Issue by AbhiPatel10** [mnnkhndlwl/mern_youtube_clone#61]
### Describe the bug

We Should make a separate file for MongoDb this will to increase code quality and faster connection.

### To Reproduce

Backend MongoDb Connection

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/76242769/222901566-9012f585-5261-4a5d-b842-b3b2918bd518.png)

**Comment by AbhiPatel10** [comment]
Please Assign this issue to me under JWOC

**Comment by mnnkhndlwl** [comment]
i don't want a separate file for mongodb connection
