### ISSUE TITLE
[Bug]: Visibility of text

### ISSUE THREAD

**Issue by zugzwang03** [mnnkhndlwl/mern_youtube_clone#62]
### Describe the bug

The text present is of black color as a result it is hardly decipherable, making it white or grey may improve readibility. 

![image](https://user-images.githubusercontent.com/95460021/222948620-7d9bd191-07c4-4ab8-9851-0d61544394de.png)

Also the text on the title of the web page is Youtube, I can change that name to VideoTube along with the web icon. 

![image](https://user-images.githubusercontent.com/95460021/222948724-d870ed0a-4041-4dc6-a6a0-8a79f2a8b524.png)

I can fix this under JWOC'23.

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/95460021/222948636-f6351181-4616-4f76-a074-fa5bb99d7399.png)

**Comment by mnnkhndlwl** [comment]
@zugzwang03 assigned

**Comment by mnnkhndlwl** [comment]
change the text color according to both dark light theme
