### ISSUE TITLE
[Bug]: make the homepage and video page responsive for mobile screens

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#64]

**Comment by Laxmankohar** [comment]
Hey @mnnkhndlwl , I want to work on this issue under JWOC. Can you please assign it to me

**Comment by mnnkhndlwl** [comment]
@Laxmankohar assigned

**Comment by parv15** [comment]
I want to work on this issue under JWOC

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/224090293-c3b2cb82-5be4-41fa-b270-303d3fcd4a05.png)
@mnnkhndlwl  bro, is it ok?

**Comment by mnnkhndlwl** [comment]
looks fine make a pr so that i can review code
