### ISSUE TITLE
[Feature]: add loading spinner to video page

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#65]
### Describe the solution you'd like

the spinner should be shown when is current video is fetching you can use spinner present in utils folder

**Comment by AbhiPatel10** [comment]
I Would like to work on this please assign this issue to me

**Comment by mnnkhndlwl** [comment]
@AbhiPatel10 have you completed the task??

**Comment by mnnkhndlwl** [comment]
@zugzwang03 assigned
