### ISSUE TITLE
Add some hover effect on video cards

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#7]

**Comment by YadnikaDabhade** [comment]
@mnnkhndlwl  can you please assign this issue to me under JWOC 2K23.I want to work on it.
Hope you allow me to work on this issue!!

**Comment by singhalaman23** [comment]
"I want to work on this issue under JWOC"

**Comment by mnnkhndlwl** [comment]
@singhalaman23 already assigned you a issue work on that first

**Comment by Atul-8115** [comment]
I want to work on this issue please assign it to me

**Comment by mnnkhndlwl** [comment]
@Atul-8115 assigned happy contributing

**Comment by singhalaman23** [comment]
> @singhalaman23 already assigned you a issue work on that first

Sure

**Comment by mnnkhndlwl** [comment]
@Atul-8115 are you still working on the issue

**Comment by Atul-8115** [comment]
> @Atul-8115 are you still working on the issue

yes I will complete it by 12:00 AM

**Comment by singhalaman23** [comment]
Hey @mnnkhndlwl , looks like no one is assigned to this issue at present. Please assign it to me under JWOC.

**Comment by mnnkhndlwl** [comment]
@singhalaman23 assigned
