### ISSUE TITLE
[Bug]: on video page two video components are showing

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#70]
### Describe the bug

![image](https://user-images.githubusercontent.com/75252077/224236295-2c5e29ea-8529-46a6-a520-ed2dc10a03fb.png)

### Expected Behavior

it should show only one video component

**Comment by Laxmankohar** [comment]
hey @mnnkhndlwl , I want to work on this issue under jwoc. can you assign it to me?

**Comment by mnnkhndlwl** [comment]
@Laxmankohar assigned

**Comment by Laxmankohar** [comment]
https://user-images.githubusercontent.com/73365025/224271762-7d81146a-62ff-4c95-b8dd-bb7b399ff42b.mp4

@mnnkhndlwl bro, can you please check it and confirm
