### ISSUE TITLE
[Feature]:  change the video component

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#75]
### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/75252077/224502558-c38cee1d-765a-4961-aacb-e7899264cba8.png)
change the whole video component like above image

**Comment by Laxmankohar** [comment]
@mnnkhndlwl , I would like to work on this issue under jwoc. Can you please assign it to me?

**Comment by mnnkhndlwl** [comment]
@Laxmankohar assigned

**Comment by Laxmankohar** [comment]
@mnnkhndlwl  bro, Can you explain a little bit more. I am getting confuse like on which part should i work.

**Comment by mnnkhndlwl** [comment]
![image](https://user-images.githubusercontent.com/75252077/224507086-d60e4468-ec6b-4fe4-82ad-1579b8195c43.png)
you have to change like , dislike button share button subscribe button or any other ui change that you think look good you can do

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/224711217-d6732963-9c36-40c6-bf5a-3da18b9e7231.png)

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/224720033-9a9daaef-4b04-4636-88eb-176d513d36ea.png)


@mnnkhndlwl bro, Have a look .

**Comment by mnnkhndlwl** [comment]
looks great

**Comment by Laxmankohar** [comment]
> looks great

I have changed the position of subscribe button, is it ok?? Can I make a PR?

**Comment by mnnkhndlwl** [comment]
Haan bro
