### ISSUE TITLE
[Bug]: timeago.js issues and source-map-loader

### ISSUE THREAD

**Issue by Regis-Loyaute** [mnnkhndlwl/mern_youtube_clone#80]
### Describe the bug

The warnings are related to unused variables and deprecated options, as well as some warnings from the source-map-loader. You can safely ignore most of these warnings, but it's still a good practice to address them.

The error messages that appear repeatedly relate to timeago.js source maps not being found. This can indicate that the timeago.js library is not installed correctly or that the file paths are incorrect. You can try to reinstall the timeago.js library to see if that resolves the issue.

### To Reproduce

I'm having this issue running the docker-compose or on my computer directly

### Additional context

youtube-react-client  | 
youtube-react-client  | > video_app@0.1.0 start
youtube-react-client  | > react-scripts start
youtube-react-client  |
youtube-react-client  | Browserslist: caniuse-lite is outdated. Please run:
youtube-react-client  |   npx update-browserslist-db@latest
youtube-react-client  |   Why you should do it regularly: https://github.com/browserslist/update-db#readme
youtube-react-client  | (node:26) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
youtube-react-client  | (Use `node --trace-deprecation ...` to show where the warning was created)
youtube-react-client  | (node:26) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
youtube-react-client  | Starting the development server...
youtube-react-client  |
youtube-react-client  | Compiled with warnings.
youtube-react-client  |
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/format.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/format.ts'
youtube-react-client  |
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/index.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/index.ts'
youtube-react-client  |
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/lang/en_US.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/lang/en_US.ts'   
youtube-react-client  |
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/lang/zh_CN.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/lang/zh_CN.ts'   
youtube-react-client  |
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/realtime.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/realtime.ts'       
youtube-react-client  |
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/register.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/register.ts'       
youtube-react-client  |
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/utils/date.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/utils/date.ts'   
youtube-react-client  |
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/utils/dom.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/utils/dom.ts'     
youtube-react-client  |
youtube-react-client  | [eslint]
youtube-react-client  | src/components/Model.jsx
youtube-react-client  |   Line 4:8:  'Avatar' is defined but never used  no-unused-vars
youtube-react-client  |
youtube-react-client  | src/pages/Video.jsx
youtube-react-client  |   Line 173:28:  'closeSnackbar' is assigned a value but never used  no-unused-vars
youtube-react-client  |   Line 176:25:  'loading' is assigned a value but never used        no-unused-vars
youtube-react-client  |
youtube-react-client  | src/redux/store.js
youtube-react-client  |   Line 1:10:  'PersistGate' is defined but never used  no-unused-vars
youtube-react-client  |
youtube-react-client  | Search for the keywords to learn more about each warning.
youtube-react-client  | To ignore, add // eslint-disable-next-line to the line before.
youtube-react-client  |
youtube-react-client  | WARNING in ./node_modules/timeago.js/esm/format.js
youtube-react-client  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/format.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/format.ts'
youtube-react-client  |
youtube-react-client  | WARNING in ./node_modules/timeago.js/esm/index.js
youtube-react-client  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/index.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/index.ts'
youtube-react-client  |
youtube-react-client  | WARNING in ./node_modules/timeago.js/esm/lang/en_US.js
youtube-react-client  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/lang/en_US.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/lang/en_US.ts'   
youtube-react-client  |
youtube-react-client  | WARNING in ./node_modules/timeago.js/esm/lang/zh_CN.js
youtube-react-client  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/lang/zh_CN.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/lang/zh_CN.ts'   
youtube-react-client  |
youtube-react-client  | WARNING in ./node_modules/timeago.js/esm/realtime.js
youtube-react-client  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/realtime.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/realtime.ts'       
youtube-react-client  |
youtube-react-client  | WARNING in ./node_modules/timeago.js/esm/register.js
youtube-react-client  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/register.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/register.ts'       
youtube-react-client  |
youtube-react-client  | WARNING in ./node_modules/timeago.js/esm/utils/date.js
youtube-react-client  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/utils/date.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/utils/date.ts'   
youtube-react-client  |
youtube-react-client  | WARNING in ./node_modules/timeago.js/esm/utils/dom.js
youtube-react-client  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/utils/dom.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/utils/dom.ts'     
youtube-react-client  |
youtube-react-client  | WARNING in [eslint]
youtube-react-client  | src/components/Model.jsx
youtube-react-client  |   Line 4:8:  'Avatar' is defined but never used  no-unused-vars
youtube-react-client  |
youtube-react-client  | src/pages/Video.jsx
youtube-react-client  |   Line 173:28:  'closeSnackbar' is assigned a value but never used  no-unused-vars
youtube-react-client  |   Line 176:25:  'loading' is assigned a value but never used        no-unused-vars
youtube-react-client  |
youtube-react-client  | src/redux/store.js
youtube-react-client  |   Line 1:10:  'PersistGate' is defined but never used  no-unused-vars
youtube-react-client  |
youtube-react-client  | webpack compiled with 9 warnings
youtube-react-client  | Compiling...
youtube-react-client  | Compiled with warnings.
youtube-react-client  |
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/format.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/format.ts'
youtube-react-client  |
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/index.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/index.ts'
youtube-react-client  |
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/lang/en_US.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/lang/en_US.ts'   
youtube-react-client  |
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/lang/zh_CN.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/lang/zh_CN.ts'   
youtube-react-client  |
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/realtime.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/realtime.ts'       
youtube-react-client  |
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/register.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/register.ts'       
youtube-react-client  |
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/utils/date.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/utils/date.ts'   
youtube-react-client  |
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/utils/dom.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/utils/dom.ts'     
youtube-react-client  |
youtube-react-client  | [eslint]
youtube-react-client  | src/components/Model.jsx
youtube-react-client  |   Line 4:8:  'Avatar' is defined but never used  no-unused-vars
youtube-react-client  |
youtube-react-client  | src/pages/Video.jsx
youtube-react-client  |   Line 173:28:  'closeSnackbar' is assigned a value but never used  no-unused-vars
youtube-react-client  |   Line 176:25:  'loading' is assigned a value but never used        no-unused-vars
youtube-react-client  |
youtube-react-client  | src/redux/store.js
youtube-react-client  |   Line 1:10:  'PersistGate' is defined but never used  no-unused-vars
youtube-react-client  |
youtube-react-client  | Search for the keywords to learn more about each warning.
youtube-react-client  | To ignore, add // eslint-disable-next-line to the line before.
youtube-react-client  |
youtube-react-client  | WARNING in ./node_modules/timeago.js/esm/format.js
youtube-react-client  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/format.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/format.ts'
youtube-react-client  |
youtube-react-client  | WARNING in ./node_modules/timeago.js/esm/index.js
youtube-react-client  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/index.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/index.ts'
youtube-react-client  |
youtube-react-client  | WARNING in ./node_modules/timeago.js/esm/lang/en_US.js
youtube-react-client  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/lang/en_US.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/lang/en_US.ts'   
youtube-react-client  |
youtube-react-client  | WARNING in ./node_modules/timeago.js/esm/lang/zh_CN.js
youtube-react-client  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/lang/zh_CN.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/lang/zh_CN.ts'   
youtube-react-client  |
youtube-react-client  | WARNING in ./node_modules/timeago.js/esm/realtime.js
youtube-react-client  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/realtime.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/realtime.ts'       
youtube-react-client  |
youtube-react-client  | WARNING in ./node_modules/timeago.js/esm/register.js
youtube-react-client  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/register.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/register.ts'       
youtube-react-client  |
youtube-react-client  | WARNING in ./node_modules/timeago.js/esm/utils/date.js
youtube-react-client  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/utils/date.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/utils/date.ts'   
youtube-react-client  |
youtube-react-client  | WARNING in ./node_modules/timeago.js/esm/utils/dom.js
youtube-react-client  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
youtube-react-client  | Failed to parse source map from '/usr/src/app/node_modules/timeago.js/src/utils/dom.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/timeago.js/src/utils/dom.ts'     
youtube-react-client  |
youtube-react-client  | WARNING in [eslint]
youtube-react-client  | src/components/Model.jsx
youtube-react-client  |   Line 4:8:  'Avatar' is defined but never used  no-unused-vars
youtube-react-client  |
youtube-react-client  | src/pages/Video.jsx
youtube-react-client  |   Line 173:28:  'closeSnackbar' is assigned a value but never used  no-unused-vars
youtube-react-client  |   Line 176:25:  'loading' is assigned a value but never used        no-unused-vars
youtube-react-client  |
youtube-react-client  | src/redux/store.js
youtube-react-client  |   Line 1:10:  'PersistGate' is defined but never used  no-unused-vars
youtube-react-client  |
youtube-react-client  | webpack compiled with 9 warnings

**Comment by Regis-Loyaute** [comment]
I managed to bypass the timeago.js by downgrading the version to 3.0.2 in the package.json...

But i still have these issues:

[eslint]
src\components\Model.jsx
  Line 4:8:  'Avatar' is defined but never used  no-unused-vars

src\pages\Video.jsx
  Line 173:28:  'closeSnackbar' is assigned a value but never used  no-unused-vars
  Line 176:25:  'loading' is assigned a value but never used        no-unused-vars

src\redux\store.js
  Line 1:10:  'PersistGate' is defined but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint]
src\components\Model.jsx
  Line 4:8:  'Avatar' is defined but never used  no-unused-vars

src\pages\Video.jsx
  Line 173:28:  'closeSnackbar' is assigned a value but never used  no-unused-vars
  Line 176:25:  'loading' is assigned a value but never used        no-unused-vars

src\redux\store.js
  Line 1:10:  'PersistGate' is defined but never used  no-unused-vars
  
  and a whitescreen on http://localhost:3000/

**Comment by mnnkhndlwl** [comment]
Did you added .env file because without that  the app will not work

**Comment by Regis-Loyaute** [comment]
here is my .env for the server:

MONGO=mongodb+srv://api-train:rVIuLxOvacRtjSqW@cluster0.vpywkhe.mongodb.net/youtube
JWT = U69!irbb@A
PORT = 3001

Do i also need to set the .env for the client ? i'm going to change the videos and pictures storage to be local.

**Comment by mnnkhndlwl** [comment]
Yeah you need to add a .env in client also that contains firebase api key I am using firebase for Google authentication and for storage

**Comment by Regis-Loyaute** [comment]
Oh ok, but is the front is supposed to now show anything without it ?

![image](https://user-images.githubusercontent.com/84942989/235702621-8abb6a4d-6b7e-4411-ae6b-e1f9b06ee4a0.png)

**Comment by mnnkhndlwl** [comment]
No frontend will not work without .env

**Comment by mnnkhndlwl** [comment]
so currently as i am storing all videos and images on firebase
but if you want to store all files locally 
then you have to use multer for uploading files locally
you have to implement an api for uploading files in server side and then store the path of that file in your database
