### ISSUE TITLE
improve the recommendation component

### ISSUE THREAD

**Issue by mnnkhndlwl** [mnnkhndlwl/mern_youtube_clone#9]
![image](https://user-images.githubusercontent.com/75252077/218269151-512074f0-7431-4d19-8710-7a9e3bdcf2c8.png)
add a space between text and the video thumbnail on the recommendation page

**Comment by singhalaman23** [comment]
"I want to work on this issue under JWOC"

**Comment by mnnkhndlwl** [comment]
assigned

**Comment by singhalaman23** [comment]
> assigned

Thankyou
